# Generated by Django 5.2.8 on 2025-11-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferNegotiationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=256, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('session_status', models.CharField(choices=[('started', 'Started'), ('done', 'Done')], default='started', max_length=25)),
                ('initial_offer', models.TextField(blank=True, default='')),
                ('offer', models.TextField(blank=True, default='')),
                ('feedback', models.TextField(blank=True, default='')),
                ('areas_for_improvement', models.TextField(blank=True, default='')),
                ('career', models.CharField(blank=True, choices=[('dev', 'Software Engineer'), ('dsgnr', 'Designer'), ('pm', 'Project Manager'), ('po', 'Product Owner'), ('mk', 'Marketer'), ('ds', 'Data Scientist'), ('cw', 'Content Writer')], default='dev', max_length=80, null=True)),
                ('seniority_level', models.CharField(blank=True, choices=[('int', 'Intern'), ('jun', 'Junior'), ('mid', 'Middle'), ('snr', 'Senior')], default='jun', max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_negotiations', to='UserProfile.userprofile')),
            ],
            options={
                'verbose_name_plural': '_Offer Negotiation Sessions',
            },
        ),
        migrations.CreateModel(
            name='NegotiationSessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_owner_type', models.CharField(choices=[('user', 'User'), ('gpt', 'GPT')], max_length=8)),
                ('text', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_greeting', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserProfile.userprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_messages', to='OfferNegotiation.offernegotiationsession')),
            ],
            options={
                'verbose_name_plural': '_Offer Negotiation message',
            },
        ),
    ]
