# Generated by Django 5.2.8 on 2025-11-23 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=30)),
                ('career', models.CharField(blank=True, choices=[('dev', 'Software Engineer'), ('dsgnr', 'Designer'), ('pm', 'Project Manager'), ('po', 'Product Owner'), ('mk', 'Marketer'), ('ds', 'Data Scientist'), ('cw', 'Content Writer')], default='dev', max_length=80, null=True)),
                ('seniority_level', models.CharField(blank=True, choices=[('int', 'Intern'), ('jun', 'Junior'), ('mid', 'Middle'), ('snr', 'Senior')], default='jun', max_length=20, null=True)),
                ('job_search_stage', models.CharField(blank=True, choices=[('act', 'Active'), ('open', 'Open to opportunities'), ('stopped', 'Not interested in any opportunities')], default='act', max_length=140, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
