# Generated by Django 5.2.8 on 2025-11-23 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('is_user', models.BooleanField(default=False, verbose_name='Is Registered User')),
                ('is_subscribed', models.BooleanField(default=True, verbose_name='Is Subscribed')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Subscription Date')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscribed emails listing',
            },
        ),
    ]
